# Generated by Django 4.2 on 2023-04-27 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_percentage_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
